name: update max apk
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
jobs:
  downl:
    name: update_apk
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout rep
        uses: actions/checkout@v4

      - name: work
      - run: \apk download\apk-to-git-master\package.json
  
    
